---
# 
#
#
# Sources:
#   - https://docs.microsoft.com/nl-nl/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-on-windows-server?view=o365-worldwide


- name: Install IIS (Web-Server and Web-Common-Http)
  ansible.windows.win_feature:
    name:
    - Windows-Defender
    state: present
